name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker JVM image
      run: |
        docker build -f src/main/docker/Dockerfile.jvm -t blazhe/it-2-jvm:latest .
        docker push blazhe/it-2-jvm:latest
