name: Quarkus CI with MongoDB

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4.6
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: rental
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Install mongosh
      run: |
        sudo apt-get install gnupg
        wget -qO- https://www.mongodb.org/static/pgp/server-7.0.asc | sudo tee /etc/apt/trusted.gpg.d/server-7.0.asc
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-mongosh
        mongosh --version

    - name: Initialize MongoDB
      run: |
        mongosh --host localhost:27017 -u admin -p admin --authenticationDatabase admin <<EOF
          db = db.getSiblingDB('rental');
          db.createUser({ user: 'rentaluser', pwd: 'rentalpass', roles: [{ role: 'readWrite', db: 'rental' }] })
          db.createCollection('rentals');
        EOF
        # Do whatever you like in here

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw clean install

    - name: Run tests
      run: ./mvnw test

    # Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Build the Docker image
    - name: Build Docker image
      run: docker build -f src/main/docker/Dockerfile.jvm -t blazhe/it-2:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to DockerHub
      run: docker push blazhe/it-2:latest
